[project]
name = "bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "py-cord[speed]>=2.8.1",
    "requests>=2.34.2",
    "ruff>=0.16.6",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "ASYNC", "FURB", "RUF", "PERF", "UP", "TRY", "PTH", "TID", "SIM", "S"]
ignore = ["E501", "S105"]
